### ISSUE TITLE
[Override] `commons/logo-external`

### ISSUE THREAD

**Issue by alexisben** [osunyorg/rennes-theme#40]
Ce partiel est un bon sujet à contribution sur le thème ! Modifier le partiel `commons/logo.html` pour qu'il soit capable d'accepter en paramètre l'url, le title en plus de l'image.

L'objectif serait d'avoir à disposition un usage tel que : 

```html
  {{ partial "commons/logo.html" (dict 
      "image" site.Params.logo.footer
      "url" "https://metropole.rennes.fr/"
      "title" "Rennes Ville et Métropole"
  }}
```

ou bien passer ces paramètres en option dans la config d'un logo : 

commons/logo.html : 
```html
  {{ partial "commons/logo.html" site.Params.logo.footer }}
```

config/_default/config.yaml
```
  logo:
    footer: 
      image: "/assets/images/logo-white.svg"
      url: "..."
      title: "..."
```

Les valeurs pour "url" et "title" sont à titre d'exemple, c'est mieux de faire ranger comme vous l'avez fait dans le fichier de config ou un fichier à part dans `/data`.
