### ISSUE TITLE
[Override] `persons/single/hero`

### ISSUE THREAD

**Issue by alexisben** [osunyorg/rennes-theme#41]
Cette ligne peut générer une erreur si les taxonomies sont configurées pour s'afficher dans le `hero`

https://github.com/osunyorg/rennes-theme/blob/9a064ebd8dc2f65d251cdd56abcd79541ffaad04/layouts/partials/persons/single/hero.html#L14

```
        "hero_text_complement" (printf "%s%s" $hero_text_complement "header/hero-chip")
```

Ça crash si on set la position des taxonomies dans le hero des personnes : 

Dans config.yaml : 

```
params:
  persons:
    single:
      taxonomies:
        position: hero
```
